### ISSUE TITLE
Hardware.md

### ISSUE THREAD

**Issue by Iftu119** [microsoft/IoT-For-Beginners#180]
Few recommendations for the [hardware](https://github.com/microsoft/IoT-For-Beginners/blob/main/hardware.md) page.

1. In the 7th line, there should be `its` instead of` it's` .
2. If we could add something like 
```
This lesson covers buying guides for  :
   [Arduino](#Arduino)
   [Raspberry Pi](#Raspberry-Pi)
   [Sensors and actuators](#Sensors-and-actuators)
   [Optional hardware](#Optional-hardware)
   [Virtual hardware](#Virtual-hardware)
```
It would help students to easily navigate in the doc.

3. In the 7th line, we see 

> The physical hardware choices are Arduino, or Raspberry Pi. Each platform has it's own upsides and downsides, and these are all covered in one of the initial lessons. Review that lesson to decide which hardware platform you are most interested in learning.

If that primary lesson is hyperlinked, it would make things easy for the users of this curriculum.

**Comment by jimbobbennett** [comment]
I've added suggestions 1 and 3. I don't think we need contents - this is a short guide listing the hardware needed, not a lesson.
