### ISSUE TITLE
Isn't void main() mot allowed in C++ ??

### ISSUE THREAD

**Issue by vishvanathan-k** [microsoft/IoT-For-Beginners#186]
I am C++ learner, i don't know about IoT. _**Just out of curiosity**_, Isn't void main() considered invalid from C++ 98.Or is it only for normal C++ and not the C++ IoT devices use ??? 
Edit: I am talking about IoT generally, bcoz I have come across some using void main() , Because its a IoT repo. Perphaps you can guide me. Thanks

**Comment by jimbobbennett** [comment]
`void main()` is definitely not standard C++. *If* your compiler supports it then you still shouldn't use it as it could have undefined behavior.

For IoT a lot of the time this a moot point as the frameworks handle this for you. For example, with Arduino, your `main` function (as in the first part of your code that is called) is `setup`, called by the Arduino framework.

**Comment by vishvanathan-k** [comment]
ohh! Thanks @jimbobbennett  for clarifying my doubt :+1: :smile:
