### ISSUE TITLE
Discussion category for class discussions

### ISSUE THREAD

**Issue by wilsonmar** [microsoft/IoT-For-Beginners#225]
A Category must be selected when adding a discussion.
But none of the existing categories (General, Q&A) seem appropriate for class discussions. How about a new category: 

**✅ Class discussions**
Respond to prompts in the readings

Only a Org Admin/Owner can add/maintain Discussion Categories. See https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository

**Comment by jimbobbennett** [comment]
I've added 👩‍🎓 Lessons as a category, and moved your IoT data discussion to this category.
