### ISSUE TITLE
Use Microsoft's automated Translator 

### ISSUE THREAD

**Issue by wilsonmar** [microsoft/IoT-For-Beginners#230]
Microsoft AI has an automatic translation service that translates text into other human languages.
https://azure.microsoft.com/en-us/services/cognitive-services/translator/
It is quite capable: https://www.inverse.com/article/42340-microsoft-ai-translation
but it would require someone to review and touch up some lines, which is a lot less work than manually translating everything.
It can be run using a pre-built model if you have PowerBI: https://docs.microsoft.com/en-us/ai-builder/flow-text-translation
That task can be automated to translate all pages using an Azure DevOps pipeline, as explained in https://community.powerbi.com/t5/Community-Blog/PowerBI-CICD-using-Azure-DevOps/ba-p/769244
@jimbobbennett if you can get a Subscription code from Microsoft we can use, I can build and run it for you.

**Comment by alihakimtaskiran** [comment]
@wilsonmar  Is it successful at saving markdown contents.(i.e Click [here](https://github.com) ---> Buraya [tıklayın](https://github.com)

**Comment by jimbobbennett** [comment]
![A gif saying well yes but actually no](https://media.giphy.com/media/SVgKToBLI6S6DUye1Y/giphy.gif)

Based on the discussion on https://github.com/microsoft/IoT-For-Beginners/issues/214, literally titled *Please stop accepting machine translated articles* I'm hesitant to push machine translations. I have no issues with them being used as a base line, but the pages do need a thorough human review to ensure correctness and appropriateness. There has been some great discussion on the right terminology to use for different things, the right voice etc.

*If* they are used with a full review then I'm ok with it, especially for languages where we have multiple contributors reviewing each others work.

**Comment by jlooper** [comment]
Closing this issue as Jim responded above

**Comment by Pandz18** [comment]
@jimbobbennett I can try to use the software to translate so that at least we can get the bases done and have people proof read them, is it ok with you?

Also how do I use the software ? The website asks me for the pricing plan....I'm a bit lost...sorry
