### ISSUE TITLE
Grove - Time of Flight Distance Sensor is out of stock

### ISSUE THREAD

**Issue by franva** [microsoft/IoT-For-Beginners#260]
Hi,

I am about to place an order for the set of hardware and found that
the Grove - Time of Flight Distance Sensor is out of stock,

Could you please provide any alternatives?

How about these 2?

https://www.aliexpress.com/item/32908633788.html?spm=a2g0o.productlist.0.0.14361772W52XlZ&algo_pvid=1aed845c-b097-414b-9bd0-6891634c6350&algo_exp_id=1aed845c-b097-414b-9bd0-6891634c6350-9

https://www.aliexpress.com/item/32737314325.html?spm=a2g0o.productlist.0.0.14361772W52XlZ&algo_pvid=1aed845c-b097-414b-9bd0-6891634c6350&algo_exp_id=1aed845c-b097-414b-9bd0-6891634c6350-14

I found that they both have 6 pins whereas the ToF sensor in the learning set only has 4 pins.

Could you please suggest that whether should I go ahead with these 2 alternatives?

Thanks

**Comment by jimbobbennett** [comment]
I'm not sure how well they would work - the grove sensor has the pins and circuitry to work with the grove libraries that are used in the code. If you use a different sensor, then you will need to work out how to interact with it yourself.

**Comment by franva** [comment]
understood. I have created a new issue which has a list of out of stock or retired hardware. 
https://github.com/microsoft/IoT-For-Beginners/issues/265

I will close this one.
