### ISSUE TITLE
刪除測驗應用程序的 PR 構建過程

### ISSUE THREAD

**Issue by ewqqrwee** [microsoft/IoT-For-Beginners#278]
https://github.com/jlooper @https://github.com/microsoft/IoT-For-Beginners/blob/b3cde63e788b047a3286693f4f5c8c56afef78ea/.github/workflows/azure-static-web-apps-brave-island-0b7c7f50f.yml#L32

**Comment by jlooper** [comment]
I don't see a problem, can you be more descriptive please?
