### ISSUE TITLE
No telemetry data received from test.mosquitto.org 

### ISSUE THREAD

**Issue by SBFallout** [microsoft/IoT-For-Beginners#303]
For the content in 4th lesson in Chapter 1: getting-started-connect-internet, I clone the code from [code-commands/virtual-device](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/4-connect-internet/code-commands/virtual-device/nightlight/app.py) and [code-commands/server](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/4-connect-internet/code-commands/server/app.py) with my own id number. But server app script return nothing. Can you please try these files again?

**Comment by jimbobbennett** [comment]
Just tested it and it works for me.

Just to confirm - you have the same ID on both client and server?

**Comment by SBFallout** [comment]
I closed this issue, because potential reason is the networking problem for Chinese student (even I can access test.mosquitto.org and I try it again with VPN)

**Comment by SBFallout** [comment]
I closed this issue, because potential reason is the networking problem for Chinese student (even I can access test.mosquitto.org and I try it again with VPN)
