### ISSUE TITLE
Can't get VS code to ssh to raspberryipi

### ISSUE THREAD

**Issue by coreyi** [microsoft/IoT-For-Beginners#311]

**Comment by coreyi** [comment]
ssh works fine from the cmd or powershell terminal, but not thru VS code (remote-SSH connect to host).  It's starts out fine but eventually dies on a "Bash: Powershell: command not found" error.  I can find lots of other people having the same problem from a couple of years ago, but I have not found a solution.  Same problem from 2 different PC's.  Any help?

Thanks

**Comment by jimbobbennett** [comment]
When you connect are you selecting Linux for the server type? This error looks like the error you would get if you select Windows as the server type.

**Comment by coreyi** [comment]
Well duh!!!. I'm so dumb to miss that 'little detail'.  Thanks a lot Jim!

**Comment by jimbobbennett** [comment]
Not dumb at all! If that works please close the issue, if not let me know and we'll see what else might be the issue.
