### ISSUE TITLE
Translation - Bangla

### ISSUE THREAD

**Issue by nihalbaig0** [microsoft/IoT-For-Beginners#312]
Created this issue to track progress and discussions for the Bangla translation.

**Comment by Iftu119** [comment]
Hi  @nihalbaig0  ! Great to see your interest.
We already have an [issue open for Bangla](https://github.com/microsoft/IoT-For-Beginners/issues/50) (aka Bengali). Please refer to that #50 and close this one.

**Comment by nihalbaig0** [comment]
I didn't see that. Thanks for notifying me.
