### ISSUE TITLE
Add timing to your plant control server navigation doesnt work

### ISSUE THREAD

**Issue by emfoster11** [microsoft/IoT-For-Beginners#315]
Link for "Add timing to your plant control" in README.md in "Automated plant watering" does not navigate like rest of the links. 
## Add timing to your plant control does not point to text "Add timing to your plant control server" appropriately and link doesn't navigate. I used these links when navigating around the lessons. Current link - [Add timing to your plant control](#add-timing-to-your-plant-control)

**Comment by jimbobbennett** [comment]
Good spot @emfoster11. Should be fixed now.
