### ISSUE TITLE
How much RAM is needed for the RPi device?

### ISSUE THREAD

**Issue by ghosh-r** [microsoft/IoT-For-Beginners#344]
I have searched through the repo, and I could not find the amount of memory necessary in the Raspberry Pi device to complete this course.

I am planning to buy an RPi 4, but unsure about the memory amount.

Which one should I buy- 2GB, 4GB, or 8GB?

Is 2 gigs of RAM enough for this course? Or should I buy another one?

**Comment by ghosh-r** [comment]
I must mention that being able to be run a full-fledged OS on the device itself is not a must for me.

I can easily use the device as a headless one and SSH into it from another device.

Please advise on the size of RAM.

**Comment by jimbobbennett** [comment]
I've just added a note to the hardware.md file to clarify this.

If you are planning to run VS Code directly on the Pi, then any Pi 4 with 2GB of RAM or more will work. The new 1GB on doesn't have enough RAM to run VS Code and the Python language server well on the device.

If you are planning to run VS Code on your PC or Mac and connect using remote SSH, then any Pi 4 will work fine, including the new 1GB version.

**Comment by jimbobbennett** [comment]
Closing this as there is also a [discussion opened on the same topic](https://github.com/microsoft/IoT-For-Beginners/discussions/343)
