### ISSUE TITLE
I'm a beginner in c++

### ISSUE THREAD

**Issue by nitin-0** [microsoft/IoT-For-Beginners#346]

**Comment by jimbobbennett** [comment]
Hey @nitin-0, welcome to this repo. As a beginner to C++ there are lots of great resources to help learn both the language and tools. I'm not sure that raising an issue in this repo is the right way to learn though. I'm going to close this, but maybe you could start a [discussion](https://github.com/microsoft/IoT-For-Beginners/discussions) and see if other folks are also learning and you can all share resources in there.
