### ISSUE TITLE
Missing declaration for response_body

### ISSUE THREAD

**Issue by marty-optum** [microsoft/IoT-For-Beginners#355]
I am going through the [Geofences](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/README.md#geofences) lesson using a Raspberry Pi.   I am using VS Code to edit remotely from a mac. 

In Step 7 of the [Task - test the geofence from the trigger](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/README.md#task---test-the-geofence-from-the-trigger) section, it appears that there is a line missing to declare the `response_body` variable.

Looking at the sample code for `__init__.py` in the [code/functions](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/code/functions/gps-trigger/geofence-trigger/__init__.py) folder, the directions in Step 7 should be updated to inform the reader to include this line below the declaration for `response`: 

`response_body = json.loads(response.text)`

If you don't add this, you will see lots of different errors show up in the logs that are output when you start the Azure function locally on your workstation.

**Comment by jimbobbennett** [comment]
Good catch. Want to raise a PR to add this?
