### ISSUE TITLE
gps-trigger Functions app with geo-fence trigger not working when deployed in the cloud

### ISSUE THREAD

**Issue by marty-optum** [microsoft/IoT-For-Beginners#356]
I am going through the [Geofences](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/README.md#geofences) lesson using a Raspberry Pi. I am using VS Code to edit remotely from a mac. The python version being used in VS Code on the mac is 3.8.2.

I already verified that the Azure function worked fine with just the iot-hub-trigger.  I also verified that both function triggers (iot-hub-trigger, geofence-trigger) were working when I ran the gps-sensor Azure function locally.

In Step 10 of the [Task - test the geofence from the trigger](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/README.md#task---test-the-geofence-from-the-trigger) section, I have uploaded the new application settings (MAPS_KEY, GEOFENCE_UDID) and re-published the gps-sensor functions app to Azure.  I am trying to verify that both function-triggers are working in Azure, but it looks like they are not  :-(

The iot-hub-trigger looks like it's working (I don't see any errors when I inspect the Monitor blade in the iot-hub-trigger function).  I am able to see new blobs written to my Azure storage account (although it seems to take a bit longer for them to show up in the Azure Storage Explorer).

The geofence-trigger, however, looks like it's not working.  I see error messages when I inspect the Monitor blade in the geofence-trigger function.  See below images for details:

![image](https://user-images.githubusercontent.com/71525323/149802809-bffb0c1c-303b-4c2f-ac65-fdd1d355b824.png)

![image](https://user-images.githubusercontent.com/71525323/149803172-7fcc11d1-3bc3-419b-b50c-cd1bc3f5f678.png)

Please advise....

**Comment by marty-optum** [comment]
@jimbobbennett , are you still monitoring and responding to these issues?  I hope I did not exceed the quota for number of issues/questions allowed :-)

I have been waiting to hear back from you in case you need me to test/try something else before I destroy these Azure resources.  I'll wait a few more days...

**Comment by jimbobbennett** [comment]
Apologies, I started a new job recently so haven been buried with getting up to speed on that.

The trigger is being run, so it is unlikely to be an issue with the consumer group or trigger settings. If it runs locally, then the settings would be correct.

Can you post your code?

**Comment by marty-optum** [comment]
Which code, specifically, do you want me to post?  And in what format (zipped and attached?) ?

**Comment by jimbobbennett** [comment]
That's weird - that library is part of tk, a graphics library.

Can you post the contents of your requirements.txt file and your __init__.py files please?

**Comment by marty-optum** [comment]
@jimbobbennett , Attached are the `requirements.txt` file, as well as the `__init__.py` file for the **geofence-trigger**.   Note: I had to add a `.txt` extension to the python file in order to convince this github interface to let me attach it.

[requirements.txt](https://github.com/microsoft/IoT-For-Beginners/files/8019707/requirements.txt)
 
[__init__ .py.txt](https://github.com/microsoft/IoT-For-Beginners/files/8019711/__init__.py.txt)

One difference I noticed between my code and the sample code (besides all the comments I added) was that I still had the following import statement.  I don't think this matters though ?

`from turtle import distance`



I assume you don't need to see the  `__init__.py` from the **iot-hub-trigger**, but I'll include it too since the postage is the same :-)
[__init__ .py.txt](https://github.com/microsoft/IoT-For-Beginners/files/8019723/__init__.py.txt)

**Comment by marty-optum** [comment]
@jimbobbennett , I think I figured it out.  My code had the following extra import statement:

`from turtle import distance`

I can't recall how it got in there (*scratch_head*), but I compared it against the [sample code in the code/functions folder](https://github.com/microsoft/IoT-For-Beginners/blob/main/3-transport/lessons/4-geofences/code/functions/gps-trigger/geofence-trigger/__init__.py) and it was not in that file.

Removing that import command from my code fixed the problem.  It works both locally and in Azure now.

**Comment by jimbobbennett** [comment]
Cool! Weird how that got there - maybe an auto added import because you typed distance and the tools got over helpful.

I'll close this now.
