### ISSUE TITLE
azure free Iot subscription for students under 18

### ISSUE THREAD

**Issue by JoseManuelPereira-Aeca** [microsoft/IoT-For-Beginners#358]
Hi,

i am a teacher trying the 12 week Iot Course in high School 3 year programming course.  There is one year course  in which we would like very much to teach this course .  We are taking the course ourselves to analise if it is possible to lecture it.

In lesson 8, an Iot subscription is needed. Some of the sudents are under 18 and the student under 18 subscription dont have a Iot service.   Is there a way to solve this situation ?
 This is a portuguese school with students email  @alunos.aecarlosamarante.pt

thank you,
J.P.

**Comment by jimbobbennett** [comment]
Sorry - we don't have a subscription for under 18s that includes IoT Hub. I've been asking for this, and we are hoping one day to be able to offer this, but no idea when.

The only way to do it would be for you or other teachers to create the hub for the class, then let them connect. This means you will need to be conscious of how many messages they send if you want to stick to the free tier, as more students means more chance to hit the 8,000 messages a day limit.
