### ISSUE TITLE
All of the Pre-lecture and Post-lecture quizzes' links are broken.

### ISSUE THREAD

**Issue by IcingTomato** [microsoft/IoT-For-Beginners#384]
![image](https://user-images.githubusercontent.com/24474531/176066607-6701b798-8199-45f7-a926-b92d0419853a.png)

**Comment by jimbobbennett** [comment]
Sorry about that - will take a look and get it back up ASAP.

**Comment by leestott** [comment]
@IcingTomato  quizzes are working again

**Comment by ArnaudBBRI** [comment]
Hello, seems to be broken again.
