### ISSUE TITLE
Raspberry PI Hardware link broken

### ISSUE THREAD

**Issue by digitalcolony** [microsoft/IoT-For-Beginners#390]
Seeeds moved the product page to here:
https://www.seeedstudio.com/Grove-Kit-with-Raspberry-Pi-4-designed-for-Microsoft-FarmBeats-for-Students-p-4872.html

**Comment by jimbobbennett** [comment]
Good spot!

It's actually this kit: https://www.seeedstudio.com/IoT-for-beginners-with-Seeed-and-Microsoft-Raspberry-Pi-Starter-Kit-p-5004.html, not the one you mention above. That's for Microsoft Farmbeats, a digital agriculture education kit.

I've fixed the link, so closing this. Thanks @digitalcolony
