### ISSUE TITLE
Using Grove Vision AI Module (I2C interface) rather than ArduCam (SPI interface)

### ISSUE THREAD

**Issue by Raunak-Singh-Inventor** [microsoft/IoT-For-Beginners#391]
I am trying to follow this tutorial with the Seeed Wio Terminal and the Grove Vision AI Module (https://wiki.seeedstudio.com/Grove-Vision-AI-Module/). 

When I try to run my code (05 stock counter) based on the 02 Fruit Quality Detector Example and connect the Grove vision AI module, the camera sets up correctly, but the image is being captured regardless of whether I connect the vision AI module or I press button C.

I think the problem is that this Grove module uses I2C interface to read data from camera rather than SPI interface as the ArduCam does. Is there any way to edit the `src/camera.h` so it can use the Grove Vision AI Module?

Thanks in advance for your help.

Code (I have added `src/config.h` & `lib/ArduCAM` to `.gitignore`): https://github.com/Raunak-Singh-Inventor/stock-counter-wio-terminal

**Comment by jimbobbennett** [comment]
There is, and I do have the hardware, but not tried it out yet. Let me try to find time to give this a go.

**Comment by Raunak-Singh-Inventor** [comment]
To complete my project I just used the official ArduCam and was able to train stock detector example. Thanks for your help.
