### ISSUE TITLE
counterfit app not opening on web browser

### ISSUE THREAD

**Issue by WEBS147** [microsoft/IoT-For-Beginners#441]
![20230130_224427](https://user-images.githubusercontent.com/123533653/215605516-443a0b5f-bda6-4b33-91f7-2bcd83d5e67e.jpg)
Each time I type the counterfit command on the vs code terminal. it shows just like the image I uploaded. but the counterfit app doesn't open on the web browser. Please what could be the problem?

**Comment by light-oj** [comment]
There is no problem at all.

Kindly visit http://127.0.0.1:5000/ or http://localhost:5000/ on your browser. The CounterFit app is already open on port 5000.

**Comment by WEBS147** [comment]
Thanks a lot for your assistance
But I still have another issue with the connection 
I have added the counterfit connection code to the app.py, opened a new terminal and ran the code. But it's still showing me disconnected. 
![20230204_194950](https://user-images.githubusercontent.com/123533653/216784517-4b42ba77-a515-4b0a-b18f-f069aa2a2345.jpg)
![20230204_195022](https://user-images.githubusercontent.com/123533653/216784521-d67a65a1-21a3-4cfe-ba03-3e2c936634fa.jpg)

**Comment by light-oj** [comment]
From the image you shared it seems you are still running on the same terminal and you ran the app.py before running the Counterfit

Try it again:
First, Run your CounterFit app on a terminal.

Visit http://127.0.0.1:5000/ or http://localhost:5000/ on your browser. The CounterFit app will be open on port 5000 like in the image you shared. 

Then, go back to your VScode click the (+) button to add a new terminal or  click on Terminal from the menu bar and click on New Terminal. 

In the new terminal, activate your virtual environment and run python3 app.py.

Go back to your browser and the Disconnected should turn to Connected.

**Comment by WEBS147** [comment]
Wow. Thanks a lot for your assistance.  It worked. I really appreciate..

**Comment by jimbobbennett** [comment]
Looks like it's now working! Thanks @light-oj for helping out here.
